spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/security
    username: sa
    password:
    driver-class-name: org.h2.Driver
  security:
    user:
      name: user
      password: 1111

  messages:
    basename: messages,errors

  jpa:
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.orm.jdbc.bind: trace #Spring Boot 3.x, hibernate6